package afpa.mra.entities;

public enum Titre {
    DESIGNER_WEB,
    CONCEPTEUR_DESIGNER_USER_INTERFACE,
    DEVELOPPEUR_WEB_WEB_MOBILE,
    CONCEPTEUR_DEVELOPPEUR_D_APPLICATIONS,
    MONTEUR_AUDIOVISUEL,
    TECHNICIEN_ASSISTANCE_INFO,
    TECHNICIEN_SUPERIEUR_SYSTEMES_ET_RESEAUX,
    AIS
}
